###
POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "serialNumber": 4,
  "name": "남기준",
  "registrationNumber": "790510-1234564",
  "genderCode": "남",
  "birthDate": "19790510204500",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "경기도 성남시 분당구 대왕판교로645번길",
  "id": "namkijun",
  "pwd": "1234",
  "email": "nam@nhnad.co.kr",
  "authority": "ROLE_MEMBER"
}

###
POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "serialNumber": 123,
  "name": "김이름",
  "registrationNumber": "981117-1234567",
  "genderCode": "여",
  "birthDate": "19981117090000",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "경상남도 김해시",
  "id": "user",
  "pwd": "1234",
  "email": "qnt012@naver.com",
  "authority": "ROLE_MEMBER"
}

###
PUT /residents/123 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "바뀐이름",
  "registrationNumber": "981117-1234567",
  "genderCode": "남",
  "birthDate": "19981117100000",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "경상남도 김해시",
  "deathDate": null,
  "deathPlaceCode": null,
  "deathPlaceAddress": null
}

###
POST /residents/4/relationship
Host: localhost:8080
Content-Type: application/json

{
  "familySerialNumber": 123,
  "relationship": "부"
}

###
PUT /residents/4/relationship/123
Host: localhost:8080
Content-Type: application/json

{
  "relationship": "자녀"
}

###
DELETE /residents/4/relationship/123
Host: localhost:8080

###
POST /residents/4/birth
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber": 123,
  "typeCode": "출생",
  "reportDate": "19981117",
  "birthReportQualifyCode": "부",
  "deathReportQualifyCode": null,
  "email": null,
  "phone": "010-1234-5678"
}

###
PUT /residents/4/birth/123
Host: localhost:8080
Content-Type: application/json

{
  "typeCode": "출생",
  "reportDate": "19981117",
  "birthReportQualifyCode": "부",
  "deathReportQualifyCode": null,
  "email": "a@b.c",
  "phone": "010-1234-5678"
}

###
DELETE /residents/4/birth/123
Host: localhost:8080

###
POST /residents/4/death
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber": 2,
  "typeCode": "사망",
  "reportDate": "20220601",
  "birthReportQualifyCode": null,
  "deathReportQualifyCode": "자녀",
  "email": null,
  "phone": "010-1234-5678"
}

###
PUT /residents/4/death/2
Host: localhost:8080
Content-Type: application/json

{
  "typeCode": "사망",
  "reportDate": "20220601",
  "birthReportQualifyCode": null,
  "deathReportQualifyCode": "자녀",
  "email": "a@b.c",
  "phone": "010-1234-5678"
}

###
DELETE /residents/4/death/2
Host: localhost:8080

###
POST /household
Host: localhost:8080
Content-Type: application/json

{
  "serialNumber": 2,
  "residentSerialNumber": 123,
  "compositionDate": "20220530",
  "compositionReasonCode": "세대분리",
  "currentAddress": "경상남도 김해시 어딘가"
}

###
DELETE /household/2
Host: localhost:8080

###
POST /household/2/movement
Host: localhost:8080
Content-Type: application/json

{
  "address": "경상남도 김해시 어딘가",
  "lastAddressYn": "N"
}

###
//{reportDate} = 전입주소를 등록한 날
PUT /household/2/movement/20220606
Host: localhost:8080
Content-Type: application/json

{
  "address": "경상남도 김해시 어딘가",
  "lastAddressYn": "Y"
}

###
//{reportDate} = 전입주소를 등록한 날
DELETE /household/2/movement/20220603
Host: localhost:8080