###
POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "serialNumber": 123,
  "name": "김이름",
  "registrationNumber": "981117-1234567",
  "genderCode": "남",
  "birthDate": "19981117090000",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "경상남도 김해시"
}

###
PUT /residents/123 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "바뀐이름",
  "registrationNumber": "981117-1234567",
  "genderCode": "남",
  "birthDate": "19981117100000",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "경상남도 김해시",
  "deathDate": null,
  "deathPlaceCode": null,
  "deathPlaceAddress": null
}

###
POST /residents/4/relationship
Host: localhost:8080
Content-Type: application/json

{
  "familySerialNumber": 123,
  "relationship": "부"
}

###
PUT /residents/4/relationship/123
Host: localhost:8080
Content-Type: application/json

{
  "relationship": "자녀"
}

###
DELETE /residents/4/relationship/123
Host: localhost:8080

###
POST /residents/{serialNumber}/birth
Host: localhost:8080
Content-Type: application/json

{

}

###
PUT /residents/{serialNumber}/birth/{targetSerialNumber}
Host: localhost:8080
Content-Type: application/json

{

}

###
DELETE /residents/{serialNumber}/birth/{targetSerialNumber}
Host: localhost:8080

###
POST /residents/{serialNumber}/death
Host: localhost:8080
Content-Type: application/json

{

}

###
PUT /residents/{serialNumber}/death/{targetSerialNumber}
Host: localhost:8080
Content-Type: application/json

{

}

###
DELETE /residents/{serialNumber}/death/{targetSerialNumber}
Host: localhost:8080

###
POST /household
Host: localhost:8080
Content-Type: application/json

{
  "serialNumber": 2,
  "residentSerialNumber": 123,
  "compositionDate": "20220530",
  "compositionReasonCode": "세대분리",
  "currentAddress": "경상남도 김해시 어딘가"
}

###
DELETE /household/2
Host: localhost:8080

###
POST /household/{householdSerialNumber}/movement
Host: localhost:8080
Content-Type: application/json

{

}

###
PUT /household/{householdSerialNumber}/movement/{reportDate}
Host: localhost:8080
Content-Type: application/json

{

}

###
DELETE /household/{householdSerialNumber}/movement/{reportDate}
Host: localhost:8080